# Generated by Django 3.2.3 on 2021-05-31 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, validators=[
                 django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('cantidad', models.PositiveIntegerField(
                    default=1, verbose_name='Cantidad')),
                ('descripcion', models.CharField(blank=True,
                 max_length=50, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
