# Generated by Django 3.2.3 on 2021-05-29 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=4, validators=[
                 django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
                ('cantidad', models.PositiveIntegerField(
                    default=1, verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
