# Generated by Django 3.2.3 on 2021-05-29 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='usuario',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='usuarios.usuario',
                verbose_name='Usuario'),
        ),
    ]
