# Generated by Django 3.2.3 on 2021-06-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_operacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
    ]
