# Generated by Django 3.2.3 on 2021-06-02 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_auto_20210602_0204'),
        ('operaciones', '0006_operacion_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='material',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='materiales.tipomaterial',
                verbose_name='Material'),
        ),
    ]
