# Generated by Django 3.2.3 on 2021-05-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True,
                 max_length=30, null=True, verbose_name='Modelo')),
                ('disponibilidad',
                 models.CharField(choices=[('DISPONIBLE',
                                            'Disponible'),
                                           ('NODISPONIBLE',
                                            'No disponible')],
                                  max_length=20,
                                  verbose_name='Disponibilidad')),
                ('descripcion', models.CharField(blank=True,
                 max_length=250, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
