# Generated by Django 3.2.3 on 2021-05-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='disponibilidad',
            field=models.CharField(
                choices=[
                    ('Disponible',
                     'Disponible'),
                    ('No Disponible',
                     'No disponible')],
                max_length=20,
                verbose_name='Disponibilidad'),
        ),
    ]
