# Generated by Django 3.2.3 on 2021-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipo_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='disponibilidad',
            field=models.CharField(
                choices=[
                    (True,
                     'Disponible'),
                    (False,
                     'No disponible')],
                max_length=20,
                verbose_name='Disponibilidad'),
        ),
    ]
